### ISSUE TITLE
Split booting from cli or api in two distinct class

### ISSUE THREAD

**Issue by qpautrat** [Evaneos/silex-rest-skeleton#2]
We can create two classes which inherits from `Application` base class and remove private methods  [bootHttpApi](https://github.com/Evaneos/silex-rest-skeleton/blob/master/app/Application.php#L81) and [bootCLI](https://github.com/Evaneos/silex-rest-skeleton/blob/master/app/Application.php#L134)

**Comment by oliviermadre** [comment]
Strategy over inheritance maybe ?

**Comment by qpautrat** [comment]
What about shared implementation ?

**Comment by jjsaunier** [comment]
I have done something similar in #8, is it what you expected ?

**Comment by qpautrat** [comment]
:+1:
